# Generated by Django 4.0.2 on 2022-02-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountgroupname', models.CharField(max_length=50)),
                ('fsitem', models.CharField(choices=[('financialperformance', 'Financial Peformance'), ('financialposition', 'Financial Position')], max_length=20)),
                ('sequenceinfs', models.SmallIntegerField()),
            ],
        ),
    ]
