# Generated by Django 4.0.2 on 2022-02-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroupsModel',
            fields=[
                ('accountgroupname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fsitem', models.CharField(choices=[('Financial Peformance', 'Financial Peformance'), ('Financial Position', 'Financial Position')], default='Financial Position', max_length=20)),
                ('sequenceinfs', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='www_users',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('realname', models.CharField(max_length=35)),
                ('customerid', models.CharField(blank=True, max_length=10)),
                ('supplierid', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=55)),
                ('showpagehelp', models.BooleanField()),
                ('showfieldhelp', models.BooleanField()),
                ('blocked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChartmasterModel',
            fields=[
                ('accountcode', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('accountname', models.CharField(max_length=50)),
                ('cashflowsactivity', models.SmallIntegerField(default=-1)),
                ('accountgroupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.accountgroupsmodel')),
            ],
        ),
    ]
