# Generated by Django 4.0.2 on 2022-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroupsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountgroupsmodel',
            name='accountgroupname',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountgroupsmodel',
            name='fsitem',
            field=models.CharField(choices=[('Financial Peformance', 'Financial Peformance'), ('Financial Position', 'Financial Position')], max_length=20),
        ),
    ]
